# Generated by Django 4.0.4 on 2022-06-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('network', models.CharField(default='', max_length=50)),
                ('cast', models.CharField(default='', max_length=200)),
                ('genre', models.CharField(default='', max_length=50)),
                ('seasons', models.IntegerField(default='', max_length=200)),
                ('episodes', models.IntegerField(default='', max_length=200)),
                ('rating', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('photo', models.URLField(default='')),
            ],
        ),
    ]
